services:
  postgres:
    image: postgres:16
    container_name: postgres_dbt
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: data_pipeline
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  python_app:
    image: python:3.11-slim
    container_name: python_app
    depends_on:
      - postgres
    working_dir: /app
    volumes:
      - .:/app
    command: sh -c "pip install -r requirements.txt && python test_connection.py"

volumes:
  postgres_data:
